# -*- mode: ruby -*-
# vi: set ft=ruby :
# To enable zsh, please set ENABLE_ZSH env var to "true" before launching vagrant up 
#   + On windows => $env:ENABLE_ZSH="true"
#   + On Linux  => export ENABLE_ZSH="true"

Vagrant.configure("2") do |config|
  config.vm.define "crc" do |crc|
    #crc.vm.box = "eazytrainingfr/ubuntu"
    #crc.vm.box_version = "1.0"
    crc.vm.box = "bento/ubuntu-22.04"
    crc.vm.box_version = "202502.21.0"
    crc.vm.network "private_network", type: "dhcp"
    crc.vm.hostname = "crc"
    crc.vm.provider "virtualbox" do |v|
      v.name = "crc"
      v.memory = 12288
      v.cpus = 6
	  v.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
    end

    crc.vm.provision :shell do |shell|
      shell.path = "install_crc.sh"
      shell.env = { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end
    
    # Étape 1 : installer les outils & ajouter vagrant au groupe libvirt
    #crc.vm.provision "shell", path: "install_tools.sh", run: "always", env: {
    #  'ENABLE_ZSH' => ENV['ENABLE_ZSH']
    #}

    # Étape 2 : après redémarrage, exécuter les commandes CRC en tant que vagrant
    #crc.vm.provision :shell do |shell|
    #  shell.name = "Configure and start CRC as vagrant user"
    #  shell.path = "install_crc_as_vagrant.sh"
    #  shell.privileged = false
    #  shell.env = {
    #    'ENABLE_ZSH' => ENV['ENABLE_ZSH']
    #  }
    #end

  end
end
