Vagrant.configure("2") do |config|
  config.vm.define "ca" do |ca|
    ca.vm.box = "geerlingguy/centos7"
    ca.vm.hostname = "ca"
    ca.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    ca.vm.network "private_network", ip: "192.168.40.10"
  end

  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "geerlingguy/centos7"
    webserver.vm.hostname = "webserver"
    webserver.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    webserver.vm.network "private_network", ip: "192.168.40.20"
  end
end
