# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "masterd" do |master|
    master.vm.box = "eazytraining/ubuntu2204"
    master.vm.box_version = "1.0"
    master.vm.network "private_network", type: "static", ip: "192.168.99.10"
    master.vm.hostname = "masterd"
    master.vm.provider "virtualbox" do |v|
      v.name = "masterd"
      v.memory = 4096
      v.cpus = 2
    end
    master.vm.provision :shell do |shell|
      shell.path = "install_swarm.sh"
      shell.args = ["master", "192.168.99.10"]
    end
  end
  workers=1
  ram_worker=2048
  cpu_worker=2
  (1..workers).each do |i|
    config.vm.define "workerd#{i}" do |worker|
      worker.vm.box = "eazytraining/ubuntu2204"
      worker.vm.box_version = "1.0"
      worker.vm.network "private_network", type: "static", ip: "192.168.99.1#{i}"
      worker.vm.hostname = "workerd#{i}"
      worker.vm.provider "virtualbox" do |v|
        v.name = "workerd#{i}"
        v.memory = ram_worker
        v.cpus = cpu_worker
      end
      worker.vm.provision :shell do |shell|
        shell.path = "install_swarm.sh"
        shell.args = ["node", "192.168.99.10"]
      end
    end
  end
end
