# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "geerlingguy/centos7"
    master.vm.network "private_network", type: "static", ip: "192.168.99.10"
    master.vm.hostname = "master"
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 4096
      v.cpus = 2
    end
    master.vm.provision :shell do |shell|
      shell.path = "install_kubernetes.sh"
      shell.args = "master"
    end
  end
  config.vm.define "worker" do |worker|
    worker.vm.box = "geerlingguy/centos7"
    worker.vm.network "private_network", type: "static", ip: "192.168.99.11"
    worker.vm.hostname = "worker"
    worker.vm.provider "virtualbox" do |v|
      v.name = "worker"
      v.memory = 2048
      v.cpus = 2
    end
    worker.vm.provision :shell do |shell|
      shell.path = "install_kubernetes.sh"
      shell.args = "node"
    end
  end
end
