Vagrant.configure("2") do |config|
  config.vm.define "ca" do |ca|
    ca.vm.box = "eazytraining/ubuntu2204"
    ca.vm.box_version = "1.0"
    ca.vm.hostname = "ca"
    ca.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    ca.vm.network "private_network", ip: "192.168.40.10"
  end

  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "eazytraining/ubuntu2204" 
    webserver.vm.box_version = "1.0"
    webserver.vm.hostname = "webserver"
    webserver.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    webserver.vm.network "private_network", ip: "192.168.40.20"
  end
end
