---
- name: Déploiement Kubernetes
  hosts: localhost
  become: yes
  roles:
    - role: kubernetes
      kubernetes_role: "{{ kubernetes_role }}"
      kubernetes_apiserver_advertise_address: "{{ kubernetes_apiserver_advertise_address }}"
      kubernetes_version: "{{ kubernetes_version | default('1.33.0') }}"
      installation_method: "{{ installation_method }}"
      kubernetes_join_command: "{{ kubernetes_join_command | default(omit) }}"
  tasks:
    - debug:
        var: kubernetes_role
