# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "puppet" do |puppet|
    puppet.vm.box = "geerlingguy/centos8"
    puppet.vm.network "private_network", type: "static", ip: "192.168.99.10"
    puppet.vm.hostname = "puppet"
    puppet.vm.provider "virtualbox" do |v|
      v.name = "puppet"
      v.memory = 4096
      v.cpus = 2
    end
    puppet.vm.provision :shell do |shell|
      shell.path = "install_puppet.sh"
      shell.args = ["master", "192.168.99.10"]
    end
  end
  clients=1
  ram_client=2048
  cpu_client=2
  (1..clients).each do |i|
    config.vm.define "client-#{i}" do |client|
      client.vm.box = "geerlingguy/centos8"
      client.vm.network "private_network", type: "static", ip: "192.168.99.1#{i}"
      client.vm.hostname = "client-#{i}"
      client.vm.provider "virtualbox" do |v|
        v.name = "client-#{i}"
        v.memory = ram_client
        v.cpus = cpu_client
      end
      client.vm.provision :shell do |shell|
        shell.path = "install_puppet.sh"
        shell.args = ["client", "192.168.99.10"]
      end
    end
  end
end
