# -*- mode: ruby -*-
# vi: set ft=ruby :
# To enable zsh, please set ENABLE_ZSH env var to "true" before launching vagrant up
#   + On Windows => $env:ENABLE_ZSH="true"
#   + On Linux  => export ENABLE_ZSH="true"

Vagrant.configure("2") do |config|
    # Define Minikube VM
    config.vm.define "minikube" do |minikube|
      # VM configuration
      # minikube.vm.box = "eazytrainingfr/ubuntu"
      minikube.vm.box = "ubuntu/jammy64"
      # minikube.vm.box_version = "1.0"
      minikube.vm.network "private_network", type: "dhcp"
      minikube.vm.hostname = "minikube"

      # VirtualBox provider settings
      minikube.vm.provider "virtualbox" do |v|
        v.name = "minikube"
        v.memory = 4096
        v.cpus = 2
      end

      # Provisioning script
      minikube.vm.provision "shell", path: "install_minikube.sh", env: { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end
  end
